version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./www:/var/www/bitrix
      - ./storage/docker/logs/nginx/:/var/log/nginx/
    depends_on:
      - php
    networks:
      - web
      - internal
    restart: always
    labels:
      - "traefik.http.routers.${APP_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${APP_NAME}-http.rule=Host(`${APP_URL_NAME}`)"
      - "traefik.http.routers.${APP_NAME}-http.middlewares=${APP_NAME}-https"
      - "traefik.http.middlewares.${APP_NAME}-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_URL_NAME}`)"
      - "traefik.http.routers.${APP_NAME}.tls=true"
      - "traefik.docker.network=web"
      - "traefik.port=80"
  php:
    build:
      context: ./docker/php
    volumes:
      - ./www:/var/www/bitrix
      - ./storage/docker/logs/php/:/var/log/php/
    depends_on:
      - mysql
    networks:
      - internal
    restart: always
    labels:
      - "traefik.enable=false"
  redis:
    build:
      context: ./docker/redis
    volumes:
      - ./storage/docker/redis:/data
    ports:
      - "6379"
    networks:
      - internal
    restart: always
    labels:
      - "traefik.enable=false"
  mysql:
    build:
      context: ./docker/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal
    restart: always
    labels:
      - "traefik.enable=false"
  memcached:
    build:
      context: ./docker/memcached
    volumes:
      - ./storage/docker/memcached:/var/lib/memcached
    ports:
      - "11211"
    depends_on:
      - php
    networks:
      - internal
    labels:
      - "traefik.enable=false"
networks:
  networks:
  web:
    external: true
  internal:
    external: false